module.exports = {
	name: "Sites clients", // optional, falls back to object key
	description: "Sites de nos clients",
	options: {
		runs: 1,
		frequency: 60, // (in minutes)
	},
	urls: [
		"http://www.agence-environnement-sante.fr/",
		"http://cotiere-transition.fr/",
		"https://grainesdesol-formation.fr",
		"https://hopandup.fr",
		"https://rvkom.fr",
		"https://annuaire.grainesdesol.fr",
		"https://ipamac.fr",
		"https://sophro-nimes.fr",
		"https://lesoinensoi.fr",
		"https://vertasouhait.fr",
		"https://senproprete.fr",
		"https://coatpet.fr",
		"https://missorigone.fr",
		"https://gymclubmulatiere.fr",
		"https://iletaitunefois-patisserie.fr",
		"https://ecoleduchapoly.fr/carte/",
		"https://www.openbar.pernod-ricard.io/",
		"https://maman-blues.fr",
		"https://www.lagonette.org",
		"https://pastene-avocat.fr",
		"https://sweetorchestra.fr",
		"https://volontairesnature.org",
		"https://mariedominiquetexier.com",
		"https://lacorditelle.com",
		"https://cofam-allaitement.org",
		"https://lacausedesparents.org",
		"https://florence-witzel-psychotherapie.fr/",
		"https://soenwer-photo.fr/",
		"https://emmanuelrodien.com",
		"https://audrey-chanonat.com",
		"https://no900.fr/",
		"https://trouvemcflyetcarlito.fr/",
		"https://www.fannygautheron.fr/",
		"https://dominiqueschwob.com/",
		"https://jardin.netlify.app/",
		"https://celinebussy.com",
		"https://laurentmallavauxphoto.fr",
		"https://pelerinageslyon.fr",
		"https://nouveaux-regards.com/",

	]
};
