module.exports = {
	name: "Sites", // optional, falls back to object key
	description: "Sites développés par l'équipe",
	options: {
		runs: 1,
		frequency: 1, // (in minutes)
	},
	urls: [
		"https://villaontherocks.fr",
		"https://moss.kromatic.fr",
		"https://grainesdesol-formation.fr",
		"https://hopandup.fr",
		"https://rvkom.fr",
		"https://annuaire.grainesdesol.fr",
		"https://ipamac.fr",
		"https://sophro-nimes.fr",
		"https://lesoinensoi.fr",
		"https://vertasouhait.fr",
		"https://senproprete.fr",
		"https://coatpet.fr",
		"https://missorigone.fr",
		"https://gymclubmulatiere.fr",
		"https://iletaitunefois-patisserie.fr",
		"https://ecoleduchapoly.fr",
		"https://ecoleduchapoly.fr/carte/",
		"https://kromatic.fr",
		"https://keeply.fr",
		"https://charlymaillefaud.fr",
		"https://eldorado-immobilier.com",
		"https://romainkoenig.com",
		"https://archi.pernod-ricard.io/",
		"https://www.openbar.pernod-ricard.io/",
		"https://romain-koenig.github.io/piscines-grand-lyon/",
		"https://monplacard.netlify.app/",
		"https://medium.com/pernod-ricard-tech/how-i-used-trello-and-reveal-js-to-automate-a-part-of-my-job-41cf103821ad",
		"https://maman-blues.fr",
		"https://forum.maman-blues.fr",
		"https://www.lagonette.org",
		"https://pastene-avocat.fr",
		"https://sweetorchestra.fr",
		"https://volontairesnature.org",
		"https://mariedominiquetexier.com",
		"https://sandrinerodrigues.fr/",
		"https://cloud.kromatic.fr/",
		"https://lacorditelle.com",
		"https://cofam-allaitement.org",
		"https://lacausedesparents.org",
		"https://florence-witzel-psychotherapie.fr/",
		"https://soenwer-photo.fr/",
		"https://agence-environnement-sante.fr",
		"https://emmanuelrodien.com",
		"https://audrey-chanonat.com",
		"https://bcmetal.fr",
		"https://no900.fr/",
		"https://birth-project.keuss.fr/",
		"https://trouvemcflyetcarlito.fr/",
		"https://www.fannygautheron.fr/",
		"https://dominiqueschwob.com/",
		"https://jardin.netlify.app/",
		"https://romain-koenig.github.io/markdown-to-pdf/",
		"https://team.pernod-ricard.io/",
		"https://celinebussy.com",
		"https://noesis3.com",
		"https://laurentmallavauxphoto.fr",
		"https://pelerinageslyon.fr",
		"https://grainesdesol.fr",
		"https://nouveaux-regards.com/",
		"https://cotiere-transition.fr",

	]
};